name: Build KDU binaries and 3p-packages
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_matrix:
    strategy:
      matrix:
        os: [macos-11,ubuntu-20.04,windows-2022]
        addrsize: [64,32]
        exclude:
          - os: ubuntu-20.04
            addrsize: 32
          - os: macos-11
            addrsize: 32
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        if: runner.os != 'Windows'
        id: py311
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip3 install -r requirements.txt

      - name: Set gcc version on Linux
        if: runner.os == 'Linux'
        run: |
          echo "CC=gcc-10" >> $GITHUB_ENV
          echo "CXX=g++-10" >> $GITHUB_ENV

      - name: Install Bash 4 and GNU sed on Mac
        if: runner.os == 'macOS'
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew update

          brew install bash
          brew install gnu-sed

          echo "/usr/local/bin" >> $GITHUB_PATH
          echo "$(brew --prefix)/opt/gnu-sed/libexec/gnubin" >> $GITHUB_PATH

      - name: Setup rclone and download the folder
        uses: beqjanus/setup-rclone@main
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Get the repo
        uses: actions/checkout@v3
        with:
          repository: beqjanus/3p-kdu
          ref: master
          token: ${{ secrets.KDU_ACCESS_TOKEN }} 
          path: .
          fetch-depth: 0
      - name: debug dump tree
        run: tree ${{github.workspace}}\
      - name: package the 3p-archive
        run: |
          cd autobuild
          autobuild configure --config-file=autobuild.xml
          autobuild build --config-file=autobuild.xml
          autobuild package --config-file=autobuild.xml
        shell: bash

      - name: rclone the private 3p packages for this platform (both 64 & 32)
        run: 'rclone copy ./autobuild/*bz2 fs_bundles:'      
